import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ReduxProvider from "@/redux/ReduxProvider";
import Footer from "@/components/shared/Footer";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/shared/Header";

const poppins = Poppins({
  weight: ["500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ReduxProvider>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
